import { Raleway } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { AdminContextProvider } from "./context/adminContext";
import Footer from "./components/Footer";
// import Mouse from "./components/Mouse";

const raleway = Raleway({
  weight: "variable",
  variable: "--raleway",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.variable}`}>
        <AdminContextProvider>
          {/* <Mouse /> */}
          <Header />
          {children}
          <Footer />
        </AdminContextProvider>
      </body>
    </html>
  );
}
